### ISSUE TITLE
Rewrite the underlying HTTP requests code

### ISSUE THREAD

**Issue by jonnywilliamson** [telegram-bot-sdk/telegram-bot-sdk#27]
**Description**  
Due to the mutiple ways that telegram needs requests to be formated to send data to them, a rewrite may be needed in the underlying HTTP request generation code (TelegramClient etc.)

- Should we use Multipart for sending everything when posting? The small penalty in converting a regular $params array to multipart style/format I think is less than the hassle of having two ways to post data to telegram.

- Find a way to easily tag which param fields need to be json encoded
- Find a way to easily tag which fields should be file inputs. (There can be more than 1).
- Deal with the `sendMediaGroup` issue of describing the files to be uploaded in one field (which is also json encoded), and letting you generate the multipart array code later using some of that information.

And I also read this blog and thought it might be very useful to seperate the $multipart payload from the request. Looks very clean.

https://blog.philipp-rieber.net/2016/02/21/creating-a-psr-7-guzzle-request-object-with-form-data/

**Comment by irazasyed** [comment]
Closed in https://github.com/telegram-bot-sdk/telegram-bot-sdk/commit/f2ce3684917aa803a6f384879e98183dab075360
