### ISSUE TITLE
error in loading config

### ISSUE THREAD

**Issue by semaster** [telegram-bot-sdk/telegram-bot-sdk#36]
- **SDK Version(s) affected**: 4@dev

- **PHP Version**: 7.4

**Description**  
in Botmanager class  we load config. Need to fix parameter to load config from telegram.php file

**How to reproduce**  

<details>
<summary>Config</summary>
$config = $this->config("bots.{$name}");
need to be replased like 
$config = $this->config("telegram.bots.{$name}");

</details>

<details>
<summary>Logs</summary>

</details>

**Possible Solution**  
$config = $this->config("bots.{$name}");
need to be replased like 
$config = $this->config("telegram.bots.{$name}");

**Additional context**

**Comment by irazasyed** [comment]
What is the error? I just re-tested everything and there are no issues.

The config method is our internal method and not Laravel config method. Hence, we don't need to do `telegram.bots.name`, there is no need of a namespace. Please post the error so that it's easier to debug.
