### ISSUE TITLE
Got error 'Typed property Telegram\Bot\Commands\Parser::$params must not be accessed before initialization' when trying to use webhook

### ISSUE THREAD

**Issue by ngocnb** [telegram-bot-sdk/telegram-bot-sdk#38]
- **Library Version**: dev-master
- **Laravel Version**: 8.3.0
- **PHP Version**: 7.4.10

**Description**  
I got error `Typed property Telegram\\Bot\\Commands\\Parser::$params must not be accessed before initialization` when trying to call webhook

**Steps To Reproduce**  
1. Set up bot, create command `/start`
2. Register webhook
3. Open bot in telegram app, call command '/start/

**Possible Solution**  
In vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/Parser.php, line 29:
```
protected ?Collection $params;
```

Should be change to
```
protected ?Collection $params = NULL;
```

**Additional Context**  

<details>
<summary>Config data</summary>

</details>

<details>
<summary>Logs</summary>
<pre>
[previous exception] [object] (Error(code: 0): Typed property Telegram\\Bot\\Commands\\Parser::$params must not be accessed before initialization at /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/Parser.php:102)
[stacktrace]
#0 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/Parser.php(163): Telegram\\Bot\\Commands\\Parser->allParams()
#1 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/Parser.php(82): Telegram\\Bot\\Commands\\Parser->argumentsPattern()
#2 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(180): Telegram\\Bot\\Commands\\Parser->arguments()
#3 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(156): Telegram\\Bot\\Commands\\CommandBus->execute()
#4 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(134): Telegram\\Bot\\Commands\\CommandBus->process()
#5 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(230): Telegram\\Bot\\Commands\\CommandBus->Telegram\\Bot\\Commands\\{closure}()
#6 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandBus.php(134): Illuminate\\Support\\Collection->each()
#7 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/CommandHandler.php(76): Telegram\\Bot\\Commands\\CommandBus->handler()
#8 /home/xxxxxxxxxxxx/workspaces/telegram-bot/vendor/telegram-bot-sdk/telegram-bot-sdk/src/Commands/Listeners/ProcessCommand.php(18): Telegram\\Bot\\Commands\\CommandHandler->processCommand()
#9 [internal function]: Telegram\\Bot\\Commands\\Listeners\\ProcessCommand->handle()
</pre>
</details>

**Comment by irazasyed** [comment]
Thanks 👍
