### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by ppalella** [telegram-bot-sdk/telegram-bot-sdk#44]
When install from composer, raise this error

```
  Argument 1 passed to Telegram\Bot\BotsManager::__construct() must be of the type array, null given, called in .../vendor/telegram-bot-sdk/telegram-bot-sdk/src/Laravel/TelegramServiceProvider.php on line 65

  at vendor/telegram-bot-sdk/telegram-bot-sdk/src/BotsManager.php:29
    25|      * TelegramManager constructor.
    26|      *
    27|      * @param array $config
    28|      */
  > 29|     public function __construct(array $config)
    30|     {
    31|         $this->config = $config;
    32|     }
    33|

```

**Comment by widianapw** [comment]
have you been solved this? I had the same issue

**Comment by drnxloc** [comment]
You must copy the config file "vendor\irazasyed\telegram-bot-sdk\src\Laravel\config\telegram.php" to the /config directory. Then reinstall

**Comment by Khakimjanovich** [comment]
> You must copy the config file "vendor\irazasyed\telegram-bot-sdk\src\Laravel\config\telegram.php" to the /config directory. Then reinstall

I tried what you said, there is no use to do this. It is happening when you call composer require command

**Comment by Khakimjanovich** [comment]
After config:cache it worked!
