### ISSUE TITLE
[Bug]: Problem with name in command class

### ISSUE THREAD

**Issue by guiluxdj** [telegram-bot-sdk/telegram-bot-sdk#71]
### PHP version

8.2.1

### Telegram Bot SDK version

3.1

### Laravel version (if any)

10

### What happened?

Hello,
I've a bug with command. It says that name is not a string but i not see error in my code.

![image](https://user-images.githubusercontent.com/26114260/230608535-6d35ec20-d91d-462d-bba4-ffb292ad466a.png)

### Error stacktrace (if any)

```shell
local.ERROR: Type of App\Telegram\Commands\HelpCommand::$name must be string (as in class Telegram\Bot\Commands\Command) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of App\\Telegram\\Commands\\HelpCommand::$name must be string (as in class Telegram\\Bot\\Commands\\Command) at /var/www/html/sm2/app/Telegram/Commands/HelpCommand.php:0)
[stacktrace]
```

### Possible Solution
VsCode underline the line in Telegram\Bot\Commands;
![image](https://user-images.githubusercontent.com/26114260/230608862-c2556a6c-5706-446f-a5be-36c14091caf5.png)

**Comment by irazasyed** [comment]
After protected you need to set `string` as the type. Ex: `protected string $name = 'help';`
